### ISSUE TITLE
Unable to clone project

### ISSUE THREAD

**Issue by detectedstealth** [PacktPublishing/Unreal-Engine-5-Shaders-and-Effects-Cookbook-2nd-Edition#1]
Says you need to buy more storage to restore the assets.

remote: Enumerating objects: 833, done.        
remote: Counting objects: 100% (833/833), done.        
remote: Compressing objects: 100% (825/825), done.        
remote: Total 833 (delta 1), reused 826 (delta 0), pack-reused 0        
Receiving objects: 100% (833/833), 115.77 KiB | 764.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Downloading Content/Assets/Chapter01/01_01/Alexs_Apt_2k.uasset (5.9 MB)
Error downloading object: Content/Assets/Chapter01/01_01/Alexs_Apt_2k.uasset (528274e): Smudge error: Error downloading Content/Assets/Chapter01/01_01/Alexs_Apt_2k.uasset (528274e3613ae912c30588c8841f19b4b7d3b37ceb8809042efa32e608d37c0f): batch response: **This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.**

**Comment by braisbr1** [comment]
Hi all,

Apologies for the delay in getting back to this conversation, as I've been away on my annual leave. I just wanted to pick this up and see if this issue has been sorted?

Best,
Brais
________________________________
From: Bruce Wade ***@***.***>
Sent: 17 October 2023 18:16
To: PacktPublishing/Unreal-Engine-5-Shaders-and-Effects-Cookbook-2nd-Edition ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PacktPublishing/Unreal-Engine-5-Shaders-and-Effects-Cookbook-2nd-Edition] Unable to clone project (Issue #1)


Says you need to buy more storage to restore the assets.

remote: Enumerating objects: 833, done.
remote: Counting objects: 100% (833/833), done.
remote: Compressing objects: 100% (825/825), done.
remote: Total 833 (delta 1), reused 826 (delta 0), pack-reused 0
Receiving objects: 100% (833/833), 115.77 KiB | 764.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Downloading Content/Assets/Chapter01/01_01/Alexs_Apt_2k.uasset (5.9 MB)
Error downloading object: Content/Assets/Chapter01/01_01/Alexs_Apt_2k.uasset (528274e): Smudge error: Error downloading Content/Assets/Chapter01/01_01/Alexs_Apt_2k.uasset (528274e3613ae912c30588c8841f19b4b7d3b37ceb8809042efa32e608d37c0f): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by braisbr1** [comment]
Hello again @detectedstealth

Just a PSA in case you weren't able to download the files before, you should now be able to download them through the link available in the front page of this repository.

Best, 
Brais
