### ISSUE TITLE
UE fails to open the project. P

### ISSUE THREAD

**Issue by ramicis** [PacktPublishing/Unreal-Engine-5-Shaders-and-Effects-Cookbook-2nd-Edition#2]
UE fails to open the project. Please explain or solve it!
Thank you

[issue](https://github.com/user-attachments/assets/60c74a13-b04f-43d4-9e66-6af2df72f750)

**Comment by braisbr1** [comment]
Hi Ramicis, 

Sorry to hear about this. I'll take a look at the issue and get in contact with the administrators of the repository to see if this can be fixed soon.

Best, 
Brais

**Comment by braisbr1** [comment]
Hello again @ramicis!

And apologies for the delay. You should now be able to download the files through the link available in the front page of this repository.

Best, 
Brais
